services:
  api:
    build:
      context: .
      dockerfile: src/FavoriteBusApp.Api/Dockerfile
    ports:
      - target: 8080
        published: 5000
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "api"
      Tranzy__ApiKey: ${Tranzy__ApiKey:?Tranzy__ApiKey is missing from env}
      ConnectionStrings__redis: "redis:6379,password=${REDIS_PASSWORD:?REDIS_PASSWORD is missing from env}"
      AllowedOrigins: "http://client:3000"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: src/favoritebusapp-client/Dockerfile
    ports:
      - target: 3000
        published: 3000
    environment:
      VITE_API_URL: "http://api:8080"
      NODE_ENV: "production"
      BROWSER: "none"
      VITE_PORT: "3000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "client"
    depends_on:
      - api
        
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
      - target: 18888
        published: 18888
    restart: unless-stopped
      
  redis:
    container_name: "redis"
    image: "docker.io/library/redis:7.4"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:?REDIS_PASSWORD is missing from env}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "redis"
    volumes:
      - "redis-volume:/data"
    ports:
      - target: 6379
        published: 6379
    command: [
      "redis-server",
      "--requirepass", "${REDIS_PASSWORD}",
      "--save", "60", "1"
    ]
    restart: unless-stopped

volumes:
  redis-volume: {}
